const AddData=[
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
    {
        name:"Adrienne Winters",
        ext:4425,
        city:"Laguna Blanca",
        startData:"2014/15/09",
        completion:"24%",
    },
    {
        name:"Alisa Horn",
        ext:9853,
        city:"Ucluelet",
        startData:"	2007/01/11",
        completion:"39%",
    },
    {
        name:"Allegra Shepherd",
        ext:2576,
        city:"Meeuwen-Gruitrode",
        startData:"2004/19/04",
        completion:"41%",
    },
]
export {AddData}