const ResponsiveData = [
    {
        id: 1,
        fname: 'Quinn',
        lname: 'Flynn',
        position: 'System Architect',
        office: 'Edinburgh',
        age: 61,
        startDate: "2011/04/25",
        salary: "$320,800",
        extn: 9497,
        email: 'q.flynn@datatables.net',
    },
    {
        id: 2,
        fname: "Garrett",
        lname: "Winters",
        position: "Chief Executive Officer (CEO)",
        office: "Tokyo",
        age: 63,
        startDate: "2011/07/25",
        salary: "$170,750",
        extn: 8422,
        email: 'g.winters@datatables.net',
    },
    {
        id: 3,
        fname: "Ashton",
        lname: "Cox",
        position: "Junior Technical Author",
        office: "San Francisco",
        age: 66,
        startDate: "2009/01/12",
        salary: "$86,000",
        extn: 1562,
        email: 'a.cox@datatables.net',
    },
    {
        id: 4,
        fname: "Cedric",
        lname: "Kelly",
        position: "Senior Javascript Developer",
        office: "Edinburgh",
        age: 22,
        startDate: "2012/03/29",
        salary: "$433,060",
        extn: 622,
        email: 'c.kelly@datatables.net',
    },
    {
        id: 5,
        fname: "Airi",
        lname: "Satou",
        position: "Accountant",
        office: "Tokyo",
        age: 33,
        startDate: "2008/11/28",
        salary: "$162,700",
        extn: 5407,
        email: 'a.satou@datatables.net',
    },
    {
        id: 6,
        fname: "Brielle",
        lname: "Williamson",
        position: "Integration Specialist",
        office: "New York",
        age: 61,
        startDate: "2012/12/02",
        salary: "$372,000",
        extn: 4804,
        email: 'b.williamson@datatables.net',
    },
    {
        id: 7,
        fname: "Herrod",
        lname: "Chandler",
        position: "Sales Assistant",
        office: "San Francisco",
        age: 59,
        startDate: "2012/08/06",
        salary: "$137,500",
        extn: 9608,
        email: 'h.chandler@datatables.net',
    },
    {
        id: 8,
        fname: "Rhona",
        lname: "Davidson",
        position: "Integration Specialist",
        office: "Tokyo",
        age: 55,
        startDate: "2010/10/14",
        salary: "$327,900",
        extn: 6200,
        email: 'r.davidson@datatables.net',
    },
    {
        id: 9,
        fname: "Colleen",
        lname: "Hurst",
        position: "Javascript Developer",
        office: "San Francisco",
        age: 39,
        startDate: "2009/09/15",
        salary: "$205,500",
        extn: 2360,
        email: 'c.hurst@datatables.net',
    },
    {
        id: 10,
        fname: "Sonya",
        lname: "Frost",
        position: "Software Engineer",
        office: "Edinburgh",
        age: 23,
        startDate: "2008/12/13",
        salary: "$103,600",
        extn: 1667,
        email: 's.frost@datatables.net',
    },
    {
        id: 11,
        fname: "Jena",
        lname: "Gaines",
        position: "Office Manager",
        office: "London ",
        age: 30,
        startDate: "2008/12/19",
        salary: "$90,560",
        extn: 3814,
        email: 'j.gaines@datatables.net',
    },
    {
        id: 12,
        fname: "Quinn",
        lname: "Flynn",
        position: "Support Lead",
        office: "Edinburgh",
        age: 22,
        startDate: "2013/03/03",
        salary: "$342,000",
        extn: 9497,
        email: 'q.flynn@datatables.net',
    },
    {
        id: 13,
        fname: "Charde",
        lname: "Marshall",
        position: "Regional Director",
        office: "San Francisco",
        age: 36,
        startDate: "2008/10/16",
        salary: "$470,600",
        extn: 6741,
        email: 'c.marshall@datatables.net',
    },
    {
        id: 14,
        fname: "Haley",
        lname: "Kennedy",
        position: "Senior Marketing Designer",
        office: "London",
        age: 43,
        startDate: "2012/12/18",
        salary: "$313,5000",
        extn: 3597,
        email: 'h.kennedy@datatables.net',
    },
]

export {ResponsiveData};