const FixedData = [
    {
        fname: 'Tiger',
        lname: 'Nixon',
        position: 'System Architect',
        office: 'Edinburgh',
        age: 61,
        date: '2011/04/25',
        salary: '$320,800',
        extn: 5421,
    },
    {
        fname: 'Garrett',
        lname: 'Winters',
        position: 'Accountant',
        office: 'Tokyo',
        age: 63,
        date: '2011/07/25',
        salary: '$170,750',
        extn: 8422,
    },
    {
        fname: 'Ashton',
        lname: 'Cox',
        position: 'Junior Technical Author',
        office: 'San Francisco',
        age: 66,
        date: '2009/01/12',
        salary: '$86,000',
        extn: 1562,
    },
    {
        fname: 'Cedric',
        lname: 'Kelly',
        position: 'Senior Javascript Developer',
        office: 'Edinburgh',
        age: 22,
        date: '2012/03/29',
        salary: '$433,060',
        extn: 6224,
    },
    {
        fname: 'Airi',
        lname: 'Satou',
        position: 'Accountant',
        office: 'Tokyo',
        age: 33,
        date: '2008/11/28',
        salary: '$162,700',
        extn: 5407,
    },
    {
        fname: 'Brielle',
        lname: 'Williamson',
        position: 'Integration Specialist',
        office: 'New York',
        age: 61,
        date: '2012/12/02',
        salary: '$372,000',
        extn: 4804,
    },
    {
        fname: 'Herrod',
        lname: 'Chandler',
        position: 'Sales Assistant',
        office: 'San Francisco',
        age: 59,
        date: '2012/08/06',
        salary: '$137,500',
        extn: 9608,
    },
    {
        fname: 'Rhona',
        lname: 'Davidson',
        position: 'Integration Specialist',
        office: 'Tokyo',
        age: 55,
        date: '2010/10/14',
        salary: '$327,900',
        extn: 6200,
    },
    {
        fname: 'Colleen',
        lname: 'Hurst',
        position: 'Javascript Developer',
        office: 'San Francisco',
        age: 39,
        date: '2009/09/15',
        salary: '$205,500',
        extn: 2360,
    },
    {
        fname: 'Sonya',
        lname: 'NixonFrost',
        position: 'Software Engineer',
        office: 'Edinburgh',
        age: 23,
        date: '2008/12/13',
        salary: '$103,600',
        extn: 1667,
    },
    
    {
        fname: 'Jena',
        lname: 'Gaines',
        position: 'Office Manager',
        office: 'London',
        age: 30,
        date: '2008/12/19',
        salary: '$90,560',
        extn: 3814,
    },
    {
        fname: 'Quinn',
        lname: 'Flynn',
        position: 'Support Lead',
        office: 'Edinburgh',
        age: 22,
        date: '2013/03/03',
        salary: '$342,000',
        extn: 9497,
    },
    {
        fname: 'Charde',
        lname: 'Marshall',
        position: 'Regional Director',
        office: 'San Francisco',
        age: 36,
        date: '2008/10/16',
        salary: '$470,600',
        extn: 6741,
    },
    {
        fname: 'Haley',
        lname: 'Kennedy',
        position: 'Senior Marketing Designer',
        office: 'London',
        age: 43,
        date: '2012/12/18',
        salary: '$313,500',
        extn: 3597,
    },
    {
        fname: 'Tatyana',
        lname: 'Fitzpatrick',
        position: 'Regional Director',
        office: 'London',
        age: 19,
        date: '2010/03/17',
        salary: '$385,750',
        extn: 1965,
    },
    {
        fname: 'Michael',
        lname: 'Silva',
        position: 'Marketing Designer',
        office: 'London',
        age: 66,
        date: '2012/11/27',
        salary: '$198,500',
        extn: 1581,
    },
    {
        fname: 'Paul',
        lname: 'Byrd',
        position: 'Chief Financial Officer (CFO)',
        office: 'New York',
        age: 64,
        date: '2010/06/09',
        salary: '$725,000',
        extn: 3059,
    },
    {
        fname: 'Gloria',
        lname: 'Little',
        position: 'Systems Administrator',
        office: 'New York',
        age: 59,
        date: '2009/04/10',
        salary: '$237,500',
        extn: 1721,
    },
    {
        fname: 'Bradley',
        lname: 'Greer',
        position: 'Software Engineer',
        office: 'London',
        age: 41,
        date: '2012/10/13',
        salary: '$132,000',
        extn: 2558,
    },
    {
        fname: 'Dai',
        lname: 'Rios',
        position: 'Personnel Lead',
        office: 'Edinburgh',
        age: 35,
        date: '2012/09/26',
        salary: '$217,500',
        extn: 2290,
    },
]

export {FixedData};